include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-eduroam
PKG_VERSION:=0.2.0
PKG_RELEASE:=1

LUCI_TITLE:=LuCI for Eduroam configuration
LUCI_DESCRIPTION:=Provides Luci for Eduroam configuration
LUCI_DEPENDS:=+luci-base +openssl-util

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
